version: '3.8'
services:
  postgres:
    image: postgres:15-alpine3.21
    container_name: postgres_pixel
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      - TZ=Europe/Moscow

  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "6379:6379"